# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
  via_ir = true
  auto_detect_solc = false
  bytecode_hash = "none"
  evm_version = "paris"
  fuzz = { runs = 1_000 }
  gas_reports = ["*"]
  optimizer = true
  optimizer_runs = 999_999
  out = "out"
  script = "script"
  solc = "0.8.26"
  src = "src"
  # test = "test"
libs = ["node_modules", "lib"]

[profile.default.env]
PRIVATE_KEY = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"

[etherscan]
# sepolia = { key = "dummy_key", url = "https://api-sepolia.etherscan.io/api", chain = 11155111 }

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
  # sepolia = "https://sepolia.infura.io/v3/eddff9ff805a4401ab7328c082ad3752" 
  sepolia = "https://virulent-delicate-wish.ethereum-sepolia.quiknode.pro/"
            # "https://ethereum-sepolia-rpc.publicnode.com"

