# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
  via_ir = true
  auto_detect_solc = false
  bytecode_hash = "none"
  evm_version = "paris"
  fuzz = { runs = 1_000 }
  gas_reports = ["*"]
  optimizer = true
  optimizer_runs = 999_999
  out = "out"
  script = "script"
  solc = "0.8.26"
  src = "src"
  # test = "test"
libs = ["node_modules", "lib"]

[profile.default.env]
PRIVATE_KEY = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"

[etherscan]
merlin_testnet = { key = "${API_KEY_ETHERSCAN}", url = "${API_URL_ETHERSCAN}", chain = 686868 }
bsc_main = { key = "${API_KEY_ETHERSCAN}", url = "${API_URL_ETHERSCAN}", chain = 56 }
sepolia = { key = "dummy_key", url = "https://api-sepolia.etherscan.io/api", chain = 11155111 }

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
  # merlin_testnet = "https://merlintestnet.blockpi.network/v1/rpc/acd38a44243a57d89dc6dc1a4dc0daed10f339c7"
  merlin_testnet = "https://merlin-testnet-rpc.merlinchain.io/" # "https://merlin-testnet-erigon.merlinchain.io/"

  merlin_mainnet = "https://rpc.merlinchain.io"
  bsc_main = "https://bsc-dataseed.binance.org"
  sepolia = "https://ethereum-sepolia-rpc.publicnode.com"

